# Generated by Django 4.0.9 on 2023-02-12 10:34

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("corp_access", "Can access tax info for own corp"),
                    ("alliance_access", "Can access tax info for alliance corps"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
