# Generated by Django 4.0.9 on 2023-02-12 15:00

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rattingtax", "0002_alter_general_options_corptax"),
    ]

    operations = [
        migrations.AddField(
            model_name="corptax",
            name="tax_rate",
            field=models.FloatField(default=0),
        ),
    ]
