# Generated by Django 4.0.9 on 2023-02-12 15:11

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("rattingtax", "0003_corptax_tax_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corptax",
            name="corporation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="eveonline.evecorporationinfo",
                unique=True,
            ),
        ),
    ]
